adjective=input("Enter an adjective: ")
animal=input("Enter an animal: ")
clothing=input("Enter a piece of clothing: ")
relative=input("Enter a type of relative (e.g., brother, aunt): ")
place=input("Enter a place: ")
print("**********")
print("Here is your madlib story:")

print(f"Today I went to a {adjective} shopping mall")
print(f"In the mall, I saw a {animal} jumping up and down in excitement")
print(f"I bought a {clothing} for my {relative}")
print(f"Then, I visited the {place} and had a great time")
print("I can't wait to go back to the mall again!")
print("The End!")
print("**********")